name: hello-world
on:
  pull_request:
    types: [closed]

jobs:
  my-job:
    if: github.ref_name == 'master' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "https://github.com/${{github.repository}} https://github.com/buildooor/opgh/pull/${{github.event.number}} branch ${{github.ref_name}} username ${{github.event.pull_request.user.login}}"